"""Generate review/confirmed_aliases.md.

The taxonomy has hundreds of entries and reviewing all of it is not a useful
task. What matters is narrower: for the technologies the ledger actually
confirms, which strings will be treated as naming them. Every alias listed here
is a phrase that may appear in a CV, so a wrong alias under a confirmed id is a
fabrication with a clean bill of health.

This is the file to review. The taxonomy itself is reference data.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from app.loaders import ROOT, Ledger, Taxonomy, load_ledger, load_taxonomy

HEADER = """# Confirmed technology aliases

Generated by `python -m app.cli.confirmed_aliases`. Do not edit by hand.

Every string below will be read as naming the technology it sits under. If a
string here names a different product, or names nothing in particular, that is a
taxonomy bug and a fabrication route: fix `vocab/taxonomy.json`.

Only ids confirmed in `evidence/ledger.json` appear. Unconfirmed and denied ids
are excluded, because their aliases cannot reach output at all.
"""


def render(ledger: Ledger, taxonomy: Taxonomy) -> str:
    lines = [HEADER]
    confirmed = ledger.confirmed_ids
    lines.append(f"\n{len(confirmed)} confirmed technolog{'y' if len(confirmed) == 1 else 'ies'}.\n")

    if not confirmed:
        lines.append(
            "\nNothing is confirmed yet, so no alias can reach output. "
            "That is the correct state for an empty ledger.\n"
        )
        return "".join(lines)

    for canonical_id in confirmed:
        entry = ledger.get(canonical_id)
        assert entry is not None
        display = taxonomy.display(canonical_id)
        lines.append(f"\n## {display}\n\n")
        lines.append(f"- id: `{canonical_id}`\n")
        lines.append(f"- depth: `{entry.depth}`\n")
        lines.append(f"- contexts: {', '.join(f'`{c}`' for c in entry.contexts) or 'none'}\n")
        if entry.services:
            lines.append(f"- services: {', '.join(f'`{s}`' for s in entry.services)}\n")
        if entry.versions:
            lines.append(f"- versions: {', '.join(f'`{v}`' for v in entry.versions)}\n")
        if entry.scope_note:
            lines.append(f"- scope note: {entry.scope_note}\n")
            lines.append(
                "  - Not enforceable in code. Shown next to the bullet in Step 4 for review.\n"
            )
        aliases = taxonomy.aliases(canonical_id) if canonical_id in taxonomy.entries else ()
        lines.append("\n  Strings that will be read as this technology:\n\n")
        for alias in aliases:
            lines.append(f"  - `{alias}`\n")

    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write review/confirmed_aliases.md.")
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)

    root = Path(args.root)
    taxonomy = load_taxonomy(root / "vocab" / "taxonomy.json")
    ledger_path = root / "evidence" / "ledger.json"
    if not ledger_path.exists():
        print(
            f"{ledger_path} does not exist yet. Yash writes it by hand; "
            f"there is nothing to review until he does."
        )
        return 0

    ledger = load_ledger(ledger_path, known_ids=taxonomy.canonical_ids)
    out = Path(args.out) if args.out else root / "review" / "confirmed_aliases.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(ledger, taxonomy), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
