"""Regenerate vocab/wordlist_en.txt.

Build-time only. The app never imports wordfreq; it reads the generated file, so
the runtime has no network dependency and works on a read-only filesystem.

Why the list is small on purpose
--------------------------------
The wordlist answers one question: is a capitalised mid-sentence token ordinary
English, or is it a product name? Every word in the list is a word that will
NOT be flagged, so a larger list is a weaker gate.

A full dictionary such as Webster's Second is about 234,000 entries and contains
enough rare nouns to shadow real product names. The top 10,000 by frequency
contains the ordinary English a CV is written in and almost no product names,
which is the calibration that fails closed.

Product names that are also common words, such as Spark or Hive, are not removed
from this list. They do not need to be: they are taxonomy aliases, and a
taxonomy match is already both a G1 finding and a JD watch-list candidate. The
heuristic only has to cover terms the taxonomy does not know.

Usage:
    pip install -r requirements-dev.txt
    python tools/build_wordlist.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

TOP_N = 10_000
OUT = Path(__file__).resolve().parent.parent / "vocab" / "wordlist_en.txt"
WORD_RE = re.compile(r"^[a-z]+$")


def main() -> int:
    try:
        from wordfreq import top_n_list
    except ImportError:
        print("wordfreq is not installed. pip install -r requirements-dev.txt", file=sys.stderr)
        return 1

    words = sorted({w for w in top_n_list("en", TOP_N) if WORD_RE.match(w)})
    header = (
        "# Generated by tools/build_wordlist.py. Do not edit by hand.\n"
        f"# Source: wordfreq top {TOP_N} English words, alphabetic only.\n"
        f"# Entries: {len(words)}\n"
    )
    OUT.write_text(header + "\n".join(words) + "\n", encoding="utf-8")
    print(f"wrote {len(words)} words to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
